---
apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: mongo
spec:
  serviceName: mongo-service
  replicas: 2
  selector:
    matchLabels:
      name: mongo
  template:
    metadata:
      name: mongo
      labels:
        name: mongo
    spec:
      containers:
      - name: mongodb
        image: mongo
        ports:
        - containerPort: 27017
        command: ["/bin/sh", "-c"]
        args:
        -   >
            mongod --replSet repset0 --bind_ip_all &&
            mongo --eval "rs.initiate({_id: 'repset0', version: 1, members: [{_id: 0, host: 'mongo-0.mongo-service:27017'}, {_id: 1, host: 'mongo-1.mongo-service:27017'}]})"
        volumeMounts:
        - name: my-db-storage
          mountPath: /data/db
  volumeClaimTemplates:
  - metadata:
      name: my-db-storage
    spec:
      accessModes: [ "ReadWriteOnce" ]
      storageClassName: standard
      resources:
        requests:
          storage: 2Gi
---
apiVersion: v1
kind: Service
metadata:
  name: mongo-service
spec:
  ports:
  - port: 27017
    targetPort: 27017
  clusterIP: None
  selector:
    name: mongo
