version: 2.1
# Set the main 'executor' for jobs, use when needed
executors:
  node:
    docker:
      - image: circleci/node:8.17
  general:
    docker:
      - image: circleci/classic
orbs:
  # use this orbs for minikube
  minikube: ccpgames/minikube@0.0.1
# our jobs
jobs:
  # job: run unit test
  unit-test: # The job's name
    executor: node # use defined executor named 'node'

    # Steps are a list of commands to run inside the docker container above
    steps:
      - checkout
      - run:
          name: Install dependencies
          command: npm install
      # for simplicity in config: no cache used
      - run:
          name: Up test environment
          command: |
            export ENV=test
            docker run -d -p 27017:27017 mongo
      - run:
          name: Run server
          command: |
            export ENV=test
            node index.js
          background: true
      - run:
          name: Wait for server healthiness
          command: while ! nc -z localhost 8080 ; do sleep 1 ; done
      - run:
          name: Run server logic tests
          command: npm test
      #mocha test, reference
      - run: mkdir junit
      - run: >
          MOCHA_FILE=./junit/test-results.xml
          ./node_modules/mocha/bin/mocha ./test
          --reporter ./node_modules/mocha-junit-reporter
      - store_test_results:
          path: ./junit
      - store_artifacts:
          path: ./junit
      - persist_to_workspace:
          root: ./
          paths:
              - ./
      - run: echo "Test phase passed"

  # job: build docker image and push to dockerhub
  build:
    executor: node
    # execution steps
    steps:
    - checkout
    - setup_remote_docker
    - attach_workspace:
        at: .
    - run:
        name: build and push
        command: |
          docker login -u $DOCKER_USER -p $DOCKER_PASS              # login first
          docker build -t vinhphuctadang/key-value-server:latest .  # build
          docker push vinhphuctadang/key-value-server:latest        # push to dockerhub
  # job: run minikube and unit test
  minikube-test:
    executor: general
    steps:
    - run: minikube/kubectl-install
    - run: minikube/minikube-install
    - run: minikube/minikube-start
    - run:
        name: deploy onto minikube
        command: |
          export ENV=minikube
          ./cmd.sh start
    - run:
        name: Run tests
        command: |
          export TEST_URL=http://$(kubectl get ing | grep key-value | awk {print $4}
          echo TEST_URL
          npm test
    - run: mkdir junit
    - run: >
        MOCHA_FILE=./junit/test-results.xml
        ./node_modules/mocha/bin/mocha ./test
        --reporter ./node_modules/mocha-junit-reporter
    - store_test_results:
        path: ./junit
    - store_artifacts:
        path: ./junit
    - persist_to_workspace:
        root: ./
        paths:
            - ./

  stage-test:
    executor: general
    steps:
    - run:
        name: deploy to gke
        command: ./cmd.sh start
    - run:
        name: install requirements
        command: |
          apt install python3 python3-pip
          pip3 install locust==1.1
    - run:
        name: cloud load test
        command: |
          cd test_load/
          locust --headless -u 1000 -r 100 --run-time 5m --csv=keyvalue
workflows:
  version: 2.1
  test: # workflow name
    jobs: # workflow job list
    - unit-test
    - build:
        requires:
        - unit-test
    # - minikube-test:
    #     requires:
    #     - build
    # - stage-test:
    #     requires:
    #     - minikube-test
