---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: key-value-deployment
  labels:
    app: key-value
spec:
  replicas: 2
  selector:
    matchLabels:
      app: key-value
  template:
    metadata:
      labels:
        app: key-value
    spec:
      containers:
      - name: key-value
        image: vinhphuctadang/key-value-server:latest
        imagePullPolicy: IfNotPresent
        ports:
        - containerPort: 8080
        env:
        - name: ENV
          value: minikube
---
apiVersion: v1
kind: Service
metadata:
  name: key-value-service
spec:
  selector:
    app: key-value
  ports:
  - protocol: TCP
    port: 80
    targetPort: 8080
